version: "3"

volumes:
  local_postgres_data: {}


services: 
  web:
    build: ./backend
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/ShakespeareAPI/bin
      - /app/ShakespeareAPI/obj
      - /app/ShakespeareAPI.Tests/bin
      - /app/ShakespeareAPI.Tests/obj
  
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
  
  client:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app